---
name: gpt
description: app for cotisation
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.1
  image: ^4.0.15
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  path_provider: ^2.0.13
  image_picker: ^0.8.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/icon.jpeg"
flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
